### ISSUE TITLE
Error in Mac, xdvipdfmx:fatal: pdf_ref_obj()

### ISSUE THREAD

**Issue by PrimeZhang** [lh1962/ModernPhysicsExperiment_PKU#1]
Hi Liang,
 Testing in your template in my mac with TexLive 2015. (I modified the statement about font.)
 And It cannot work with error

xdvipdfmx:fatal: pdf_ref_obj(): passed invalid object. Output file removed.

 It seems other guys have same error under TexLive 2015.

**Comment by lh1962** [comment]
Try to comment the codes of graphics, it might be some problems with the .eps files

**Comment by PrimeZhang** [comment]
Problem solved if I manually turn the eps file to pdf or jpeg.
